BellmanFord : main.o Graph.o
				clang++ -o BellmanFord main.o Graph.o
main.o : main.cpp Graph.h
				clang++ -c -std=c++17 main.cpp

Graph.o : Graph.cpp Graph.h
				clang++ -c -std=c++17 Graph.cpp
